Django project/config/urls.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : config/urls.py
# Author : Team
# ---------------------------------------------------------------------------

"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('facturasieli.urls')),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = i18n_patterns(*urlpatterns)

Django project/facturasieli/urls.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/urls.py
# Author : Team
# ---------------------------------------------------------------------------

from django.contrib.auth import views as auth_views
from django.urls import path

from facturasieli import views


app_name = 'facturasieli'
urlpatterns = [
    path('', views.index, name='index'),

    path('register/', views.register, name='register'),
    path('welcome/', views.welcome, name='welcome'),

    path('custom_login/', views.custom_log_in, name='custom_log_in'),
    path('otp_validation/', views.otp_validation, name='otp_validation'),
    # path('accounts/login/', auth_views.LoginView.as_view(), name='log_in'),

    path('logout/', views.log_out, name='log_out'),
    path('goodbye/', views.goodbye, name='goodbye'),

    path('public_profile/<int:user_id>/', views.public_profile, name='public_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    path('service_form/', views.handle_service, name='service_form'),
    path('service/<int:company_id>/', views.display_service, name='service'),
    path('show_service/<int:service_id>/', views.show_service, name='show_service'),
    path('delete_service/<int:service_id>/', views.delete_service, name='delete_service'),

    path('invoices/<int:invoice_id>/verify/', views.verify_invoice_view, name='verify_invoice'),

    # Added by Nabil
    path('list_invoices/<int:company_id>/', views.list_invoices, name='list_invoices'),
    path('invoice_details/<int:invoice_id>/', views.invoice_details, name='invoice_details'),

    path('invoice/', views.invoice_view, name='invoice_form'),
    path('invoice/success/', views.invoice_success, name='invoice_success'),
    
    path('notification/', views.show_notification, name='show_notification'),

]

Django project/facturasieli/models/Address.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Address.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _


class Address(models.Model):
    number = models.IntegerField(_("Number"))
    street = models.CharField(_("Street"), max_length=255)
    addings = models.CharField(_("Addings"), max_length=255, blank=True, null=True)
    zip_code = models.IntegerField(_("Zip Code"))
    city = models.CharField(_("City"), max_length=255)
    country = models.CharField(_("Country"), max_length=255)

    def __str__(self):
        return f'{self.number} {self.street}, {self.city}, {self.country}'

Django project/facturasieli/models/Company.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Company.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _

from facturasieli.models import Address


class Company(models.Model):
    siret = models.CharField(_("SIRET"), max_length=15)
    name = models.CharField(_("Name"), max_length=255)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='companies')

    def __str__(self):
        return self.name

Django project/facturasieli/models/Invoice.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Invoice.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _
from facturasieli.models import Address, Service


class Invoice(models.Model):
    PENDING = 'Pending'
    VERIFIED = 'Verified'
    PAID = 'Paid'
    STATUS_CHOICES = [
        (PENDING, _('Pending')),
        (VERIFIED, _('Verified')),
        (PAID, _('Paid'))
    ]

    invoice_number = models.IntegerField(_("Invoice Number"))
    issue_date = models.DateField(_("Issue Date"))
    due_date = models.DateField(_("Due Date"))
    kind_of_payment = models.CharField(_("Kind of Payment"), max_length=255, default=_('Bank Transfer'))
    name_provider = models.CharField(_("Provider Name"), max_length=255)
    name_client = models.CharField(_("Client Name"), max_length=255)
    amount_excluding_tax = models.FloatField(_("Amount Excluding Tax"))
    tax = models.FloatField(_("Tax"))
    status = models.CharField(_("Status"), max_length=50, choices=STATUS_CHOICES)
    provider_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='invoices_as_provider')
    client_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='invoices_as_client')
    #service = models.ForeignKey('Service', on_delete=models.CASCADE, related_name='related_service_invoice', null=True, blank=True)

    def __str__(self):
        return f'Invoice {self.invoice_number} - {self.status}'

Django project/facturasieli/models/Notification.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Notification.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _

from facturasieli.models.Company import Company
from facturasieli.models.NotificationType import NotificationType


class Notification(models.Model):
    send_at = models.DateField(_("Send At"))
    type = models.IntegerField(_("Type"), choices=NotificationType.choices, default=NotificationType.DEMANDE_FACTURE)
    service_title = models.CharField(_("Service Title"), max_length=255)
    company_sender = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_sender')
    company_receiver = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_receiver')

Django project/facturasieli/models/NotificationType.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/NotificationType.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _


class NotificationType(models.IntegerChoices):
    DEMANDE_FACTURE = 1, _('Invoice Request')
    FACTURE_SOUMISE = 2, _('Invoice Submitted')
    FACTURE_VERIFIEE = 3, _('Invoice Verified')
    FACTURE_REJETEE = 4, _('Invoice Rejected')
    FACTURE_PAYEE = 5, _('Invoice Paid')

Django project/facturasieli/models/OTP.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/OTP.py
# Author : Brice
# ---------------------------------------------------------------------------

from django.contrib.auth.models import User
from django.db import models

from facturasieli.models.utils import compute_expiration_timestamp


class OTP(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    creation_timestamp = models.DateTimeField(auto_now_add=True)
    expiration_timestamp = models.DateTimeField(default=compute_expiration_timestamp)
    otp = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username

Django project/facturasieli/models/OTPModel.py
# facturasieli/models/OTPModel.py
from django.contrib.auth.models import User
from django.db import models

from facturasieli.models.utils import compute_expiration_timestamp


class OTPModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    creation_timestamp = models.DateTimeField(auto_now_add=True)
    expiration_timestamp = models.DateTimeField(default=compute_expiration_timestamp)
    otp = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username

Django project/facturasieli/models/Role.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Role.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models


class Role(models.Model):
    role = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.role

Django project/facturasieli/forms/InvoiceForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/InvoiceForm.py
# Author : Margaux
# ---------------------------------------------------------------------------

from django import forms

from facturasieli.models import Invoice


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = [
            'invoice_number', 'issue_date', 'due_date', 'kind_of_payment',
            'name_provider', 'name_client', 'amount_excluding_tax', 'tax',
            'status', 'provider_address', 'client_address'
        ]

Django project/facturasieli/forms/OTPForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/OTPForm.py
# Author : Brice
# ---------------------------------------------------------------------------

from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from facturasieli.models import OTP


class OTPForm(ModelForm):
    class Meta:
        model = OTP
        fields = ['otp']

Django project/facturasieli/forms/ProfileForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/ProfileForm.py
# Author : Zineb
# ---------------------------------------------------------------------------

from django import forms
from django.utils.translation import gettext_lazy as _

from facturasieli.models import Company, Profile, Role


class ProfileForm(forms.ModelForm):
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"), widget=forms.PasswordInput)
    role = forms.ModelMultipleChoiceField(queryset=Role.objects.all(), widget=forms.CheckboxSelectMultiple, required=True)
    company = forms.ModelChoiceField(queryset=Company.objects.all(), required=True)

    class Meta:
        model = Profile
        fields = ('email', 'first_name', 'last_name', 'role', 'company')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Passwords don't match"))
        return password2

    def save(self, commit=True):
        profile = super().save(commit=False)
        profile.set_password(self.cleaned_data["password1"])
        if commit:
            profile.save()
            self.save_m2m()  # Save the many-to-many data for roles
        return profile

Django project/facturasieli/forms/ServiceForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/ServiceForm.py
# Author : Morice
# ---------------------------------------------------------------------------

from django import forms
from django.utils.translation import gettext_lazy as _

from facturasieli.models import Service


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ["title", "description", "intervention_start_date", "intervention_end_date", "company_provider"]  
        labels = {
            'title': _('Service Title:'),
            'description': _('Description:'),
            'intervention_start_date': _('Start of the service:'),
            'intervention_end_date': _('End of the service:'),
            'company_provider': _('Company:'),
        }

Django project/facturasieli/forms/VerificationForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/VerificationForm.py
# Author : Zineb
# ---------------------------------------------------------------------------

from django import forms

from facturasieli.models import Verification


class VerificationForm(forms.ModelForm):
    class Meta:
        model = Verification
        fields = ['comments']

    STATUS_CHOICES = [
        (1, 'Verified'),
        (2, 'rejected')
    ]

    status = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect)
    

Django project/facturasieli/forms/service_form.py
from django.forms import ModelForm

Django project/facturasieli/views.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/views.py
# Author : Team
# ---------------------------------------------------------------------------

from facturasieli.views.index import index

from facturasieli.views.registration import register
from facturasieli.views.registration import create_otp
from facturasieli.views.registration import send_otp_mail
from facturasieli.views.registration import otp_validation
from facturasieli.views.registration import custom_log_in
from facturasieli.views.registration import log_out

from facturasieli.views.registration.transitions import welcome
from facturasieli.views.registration.transitions import goodbye

from facturasieli.views.profile import public_profile
from facturasieli.views.profile import edit_profile

from facturasieli.views.service import handle_service
from facturasieli.views.service import display_service
from facturasieli.views.service import delete_service

from facturasieli.views.verification import verify_invoice_view
from facturasieli.views.invoice import invoice_view, invoice_success, list_invoices

Django project/facturasieli/templates/base.html
<!---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/templates/base.html
# Author : Team
# -------------------------------------------------------------------------->

{% load static %}
{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel='stylesheet' href="{% static 'facturasieli/notification/css/display_notification_detail.css' %}"  >

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script src="{% static 'facturasieli/notification/js/notification.js' %}"></script>

    <title>FacturaSieli</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'facturasieli:index' %}">FacturaSieli</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'facturasieli:index' %}">🏠 {% translate 'Home' %}</a>
              </li>
              {% if user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'facturasieli:public_profile' user.id %}">👤 {% translate 'Profile' %}</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'facturasieli:service' request.profile.company_id %}">{% translate 'Services' %}</a>
              </li>

              <li class="nav-item">
                <a class="nav-link" href="{% url 'facturasieli:list_invoices' request.profile.company_id %}">{% translate 'Invoices' %}</a>
              </li>

              <li class="nav-item">
                <a class="nav-link text-body" href="{% url 'facturasieli:show_notification' %}" > 
                  {% translate 'Notifications' %}
                  <span class="badge rounded-pill badge-notification bg-danger">9+</span>
                </a>
              </li>
              {% endif %}
              {% if user.username %}
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    {% translate 'Language' %}
                </a>
                <ul class="dropdown-menu">  
                  <li><a class="dropdown-item" href="/fr/">🇫🇷 {% translate 'French' %}</a></li>
                  <li><a class="dropdown-item" href="/en/">🇬🇧 {% translate 'English' %}</a></li>
                </ul>
              </li>
              {% endif %}
            </ul>

            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">{% translate 'Search' %}</button>
            </form>
            <div>

                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'facturasieli:log_out' %}">↪️ {% translate 'Disconnection' %}</a>
                    </li>
                    {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'facturasieli:custom_log_in' %}">🔐 {% translate 'Connection' %}</a></li>
                    {% endif %}
                </ul>
            </div>
          </div>
        </div>
      </nav>
      <main class="container">
        <div class="text-center">
            <h2 class="mt-4 mb-4">✨ 📒 &nbsp; {% translate 'Welcome to FacturaSieli' %} {{ request.profile.first_name|slice:":1"|upper }}{{ request.profile.first_name|slice:"1:"|lower }}{% translate '!' %} &nbsp; 📒 ✨</h2>
        </div>
        <div class="container d-flex justify-content-center">
            <div class="w-100">
                {% block content %}
                {% endblock %}
            </div>
        </div>
      </main>
</body>
</html>