Django project/config/urls.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : config/urls.py
# Author : Team
# ---------------------------------------------------------------------------

"""
URL configuration for config project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""

from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('facturasieli.urls')),
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns = i18n_patterns(*urlpatterns)

Django project/facturasieli/urls.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/urls.py
# Author : Team
# ---------------------------------------------------------------------------

from django.contrib.auth import views as auth_views
from django.urls import path

from facturasieli import views


app_name = 'facturasieli'
urlpatterns = [
    path('', views.index, name='index'),

    path('register/', views.register, name='register'),
    path('welcome/', views.welcome, name='welcome'),

    path('custom_login/', views.custom_log_in, name='custom_log_in'),
    path('otp_validation/', views.otp_validation, name='otp_validation'),
    # path('accounts/login/', auth_views.LoginView.as_view(), name='log_in'),

    path('logout/', views.log_out, name='log_out'),
    path('goodbye/', views.goodbye, name='goodbye'),

    path('public_profile/<int:user_id>/', views.public_profile, name='public_profile'),
    path('edit_profile/', views.edit_profile, name='edit_profile'),

    path('service_form/', views.handle_service, name='service_form'),
    path('service/<int:company_id>/', views.display_service, name='service'),
    path('show_service/<int:service_id>/', views.show_service, name='show_service'),
    path('delete_service/<int:service_id>/', views.delete_service, name='delete_service'),

    path('invoices/<int:invoice_id>/verify/', views.verify_invoice_view, name='verify_invoice'),

    # Added by Nabil
    path('list_invoices/<int:company_id>/', views.list_invoices, name='list_invoices'),
    path('invoice_details/<int:invoice_id>/', views.invoice_details, name='invoice_details'),

    path('invoice/', views.invoice_view, name='invoice_form'),
    path('invoice/success/', views.invoice_success, name='invoice_success'),
    
    path('notification/', views.show_notification, name='show_notification'),

]

Django project/facturasieli/models/Address.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Address.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _


class Address(models.Model):
    number = models.IntegerField(_("Number"))
    street = models.CharField(_("Street"), max_length=255)
    addings = models.CharField(_("Addings"), max_length=255, blank=True, null=True)
    zip_code = models.IntegerField(_("Zip Code"))
    city = models.CharField(_("City"), max_length=255)
    country = models.CharField(_("Country"), max_length=255)

    def __str__(self):
        return f'{self.number} {self.street}, {self.city}, {self.country}'

Django project/facturasieli/models/Company.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Company.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _

from facturasieli.models import Address


class Company(models.Model):
    siret = models.CharField(_("SIRET"), max_length=15)
    name = models.CharField(_("Name"), max_length=255)
    address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='companies')

    def __str__(self):
        return self.name

Django project/facturasieli/models/Invoice.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Invoice.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _
from facturasieli.models import Address, Service


class Invoice(models.Model):
    PENDING = 'Pending'
    VERIFIED = 'Verified'
    PAID = 'Paid'
    STATUS_CHOICES = [
        (PENDING, _('Pending')),
        (VERIFIED, _('Verified')),
        (PAID, _('Paid'))
    ]

    invoice_number = models.IntegerField(_("Invoice Number"))
    issue_date = models.DateField(_("Issue Date"))
    due_date = models.DateField(_("Due Date"))
    kind_of_payment = models.CharField(_("Kind of Payment"), max_length=255, default=_('Bank Transfer'))
    name_provider = models.CharField(_("Provider Name"), max_length=255)
    name_client = models.CharField(_("Client Name"), max_length=255)
    amount_excluding_tax = models.FloatField(_("Amount Excluding Tax"))
    tax = models.FloatField(_("Tax"))
    status = models.CharField(_("Status"), max_length=50, choices=STATUS_CHOICES)
    provider_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='invoices_as_provider')
    client_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name='invoices_as_client')
    #service = models.ForeignKey('Service', on_delete=models.CASCADE, related_name='related_service_invoice', null=True, blank=True)

    def __str__(self):
        return f'Invoice {self.invoice_number} - {self.status}'

Django project/facturasieli/models/Notification.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Notification.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _

from facturasieli.models.Company import Company
from facturasieli.models.NotificationType import NotificationType


class Notification(models.Model):
    send_at = models.DateField(_("Send At"))
    type = models.IntegerField(_("Type"), choices=NotificationType.choices, default=NotificationType.DEMANDE_FACTURE)
    service_title = models.CharField(_("Service Title"), max_length=255)
    company_sender = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_sender')
    company_receiver = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='company_receiver')

Django project/facturasieli/models/NotificationType.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/NotificationType.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models
from django.utils.translation import gettext_lazy as _


class NotificationType(models.IntegerChoices):
    DEMANDE_FACTURE = 1, _('Invoice Request')
    FACTURE_SOUMISE = 2, _('Invoice Submitted')
    FACTURE_VERIFIEE = 3, _('Invoice Verified')
    FACTURE_REJETEE = 4, _('Invoice Rejected')
    FACTURE_PAYEE = 5, _('Invoice Paid')

Django project/facturasieli/models/OTP.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/OTP.py
# Author : Brice
# ---------------------------------------------------------------------------

from django.contrib.auth.models import User
from django.db import models

from facturasieli.models.utils import compute_expiration_timestamp


class OTP(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    creation_timestamp = models.DateTimeField(auto_now_add=True)
    expiration_timestamp = models.DateTimeField(default=compute_expiration_timestamp)
    otp = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username

Django project/facturasieli/models/OTPModel.py
# facturasieli/models/OTPModel.py
from django.contrib.auth.models import User
from django.db import models

from facturasieli.models.utils import compute_expiration_timestamp


class OTPModel(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    creation_timestamp = models.DateTimeField(auto_now_add=True)
    expiration_timestamp = models.DateTimeField(default=compute_expiration_timestamp)
    otp = models.CharField(max_length=10)

    def __str__(self):
        return self.user.username

Django project/facturasieli/models/Role.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/models/Role.py
# Author : Arnaud, Zineb
# ---------------------------------------------------------------------------

from django.db import models


class Role(models.Model):
    role = models.CharField(max_length=255)
    description = models.CharField(max_length=255)

    def __str__(self):
        return self.role

Django project/facturasieli/forms/InvoiceForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/InvoiceForm.py
# Author : Margaux
# ---------------------------------------------------------------------------

from django import forms

from facturasieli.models import Invoice


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        fields = [
            'invoice_number', 'issue_date', 'due_date', 'kind_of_payment',
            'name_provider', 'name_client', 'amount_excluding_tax', 'tax',
            'status', 'provider_address', 'client_address'
        ]

Django project/facturasieli/forms/OTPForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/OTPForm.py
# Author : Brice
# ---------------------------------------------------------------------------

from django.forms import ModelForm
from django.utils.translation import gettext_lazy as _

from facturasieli.models import OTP


class OTPForm(ModelForm):
    class Meta:
        model = OTP
        fields = ['otp']

Django project/facturasieli/forms/ProfileForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/ProfileForm.py
# Author : Zineb
# ---------------------------------------------------------------------------

from django import forms
from django.utils.translation import gettext_lazy as _

from facturasieli.models import Company, Profile, Role


class ProfileForm(forms.ModelForm):
    password1 = forms.CharField(label=_("Password"), widget=forms.PasswordInput)
    password2 = forms.CharField(label=_("Password confirmation"), widget=forms.PasswordInput)
    role = forms.ModelMultipleChoiceField(queryset=Role.objects.all(), widget=forms.CheckboxSelectMultiple, required=True)
    company = forms.ModelChoiceField(queryset=Company.objects.all(), required=True)

    class Meta:
        model = Profile
        fields = ('email', 'first_name', 'last_name', 'role', 'company')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(_("Passwords don't match"))
        return password2

    def save(self, commit=True):
        profile = super().save(commit=False)
        profile.set_password(self.cleaned_data["password1"])
        if commit:
            profile.save()
            self.save_m2m()  # Save the many-to-many data for roles
        return profile

Django project/facturasieli/forms/ServiceForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/ServiceForm.py
# Author : Morice
# ---------------------------------------------------------------------------

from django import forms
from django.utils.translation import gettext_lazy as _

from facturasieli.models import Service


class ServiceForm(forms.ModelForm):
    class Meta:
        model = Service
        fields = ["title", "description", "intervention_start_date", "intervention_end_date", "company_provider"]  
        labels = {
            'title': _('Service Title:'),
            'description': _('Description:'),
            'intervention_start_date': _('Start of the service:'),
            'intervention_end_date': _('End of the service:'),
            'company_provider': _('Company:'),
        }

Django project/facturasieli/forms/VerificationForm.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/forms/VerificationForm.py
# Author : Zineb
# ---------------------------------------------------------------------------

from django import forms

from facturasieli.models import Verification


class VerificationForm(forms.ModelForm):
    class Meta:
        model = Verification
        fields = ['comments']

    STATUS_CHOICES = [
        (1, 'Verified'),
        (2, 'rejected')
    ]

    status = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.RadioSelect)
    

Django project/facturasieli/forms/service_form.py
from django.forms import ModelForm

Django project/facturasieli/views.py
# ---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/views.py
# Author : Team
# ---------------------------------------------------------------------------

from facturasieli.views.index import index

from facturasieli.views.registration import register
from facturasieli.views.registration import create_otp
from facturasieli.views.registration import send_otp_mail
from facturasieli.views.registration import otp_validation
from facturasieli.views.registration import custom_log_in
from facturasieli.views.registration import log_out

from facturasieli.views.registration.transitions import welcome
from facturasieli.views.registration.transitions import goodbye

from facturasieli.views.profile import public_profile
from facturasieli.views.profile import edit_profile

from facturasieli.views.service import handle_service
from facturasieli.views.service import display_service
from facturasieli.views.service import delete_service

from facturasieli.views.verification import verify_invoice_view
from facturasieli.views.invoice import invoice_view, invoice_success, list_invoices

Django project/facturasieli/templates/facturasieli/invoice/invoice_details.html
<!---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/templates/facturasieli/invoice/invoice_details.html
# Author : Nabil
# -------------------------------------------------------------------------->

{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block content %}

{% if invoice %}
<div class="card" style="width: 18rem;">
    <img src="{% static 'images/invoiceLucie.png' %}" class="card-img-top" alt="invoice">
    <div class="card-body">
        <h5 class="card-title">N° {{ invoice.invoice_number }}</h5>
        <strong>{% translate 'Date:' %}</strong><small> {{ invoice.due_date }}</small> 
        <p class="card-text"></p>
    </div>
    <ul class="list-group list-group-flush">
        <li class="list-group-item">
        <strong>{% translate 'Provider:' %}</strong> {{ invoice.name_provider }} 
    </li>
        <li class="list-group-item">
        <strong>{% translate 'Client:' %}</strong> {{ invoice.name_client }} 
    </li>
        <li class="list-group-item">
        <strong>{% translate 'Date de paiement:' %}</strong><small> {{ invoice.due_date }}</small>    
    </li>
        <li class="list-group-item">
        <strong>{% translate 'Price:' %}</strong> {{ invoice.amount_excluding_tax }} € 
        <strong>{% translate 'VAT:' %}</strong> {{ invoice.tax }}
    </li>
        <li class="list-group-item">
        <strong>{% translate 'Amount:' %}</strong> {{ total }} €  
        <i class="text-primary"><u>{{ invoice.kind_of_payment }}</u></i> 
        </li>
        <li class="list-group-item">
        <strong class="text-danger">{{ invoice.status }}</strong>  
        </li>
    </ul>
  
</div>
{% else %}
<div>
    <p>No invoice registered yet.</p>
</div>
{% endif %}

{% endblock %}

Django project/facturasieli/templates/facturasieli/invoice/list_invoices.html
<!---------------------------------------------------------------------------
#                    F a c t u r a S i e l i   ( 2 0 2 4 )
# ---------------------------------------------------------------------------
# File   : facturasieli/templates/facturasieli/invoice/list_invoices.html
# Author : Nabil
# -------------------------------------------------------------------------->

{% extends 'base.html' %}

{% load static %}
{% load i18n %}

{% block content %}

<div class="mt-4">   
    <h3 class="text-center mt-3">{% translate 'Your outgoing invoices' %}</h3>
    {% if outgoing_invoices %}
    <div class="d-flex justify-content-center mt-4">
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">{% translate 'Invoice Number' %}</th>
                <th scope="col">{% translate 'Issue date' %}</th>
                <th scope="col">{% translate 'Due date' %}</th>
                <th scope="col">{% translate 'Customer' %}</th>
                <th scope="col">{% translate 'Amount' %}</th>
                <th scope="col">{% translate 'Status' %}</th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                    {% for invoice in outgoing_invoices %}
                        <tr>
                            <th scope="row">{{ invoice.invoice_number }}</th>
                            <td>{{ invoice.issue_date }}</td>
                            <td>{{ invoice.due_date }}</td>
                            <td>{{ invoice.name_client }}</td>
                            <td>{{ invoice.amount_excluding_tax }}</td>
                            <td>{{ invoice.status }}</td>
                            <td><a href="{% url 'facturasieli:invoice_details' invoice.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/>
                                    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/>
                                </svg>
                            </a></td>
                        </tr>
                    {% endfor %}
                {% else %}
                <div>
                    <p>No invoice registered yet.</p>
                </div>
                {% endif %}
            </tbody>
        </table>
    </div>


    <h3 class="text-center mt-3">{% translate 'Your incoming invoices' %}</h3>
    <div class="d-flex justify-content-center mt-4">
        
        {% if incoming_invoices %}
        <table class="table table-striped">
            <thead>
                <tr>
                <th scope="col">{% translate 'Invoice Number' %}</th>
                <th scope="col">{% translate 'Issue date' %}</th>
                <th scope="col">{% translate 'Due date' %}</th>
                <th scope="col">{% translate 'Provider' %}</th>
                <th scope="col">{% translate 'Amount' %}</th>
                <th scope="col">{% translate 'Status' %}</th>
                <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                    {% for invoice in incoming_invoices %}
                        <tr>
                            <th scope="row">{{ invoice.invoice_number }}</th>
                            <td>{{ invoice.issue_date }}</td>
                            <td>{{ invoice.due_date }}</td>
                            <td>{{ invoice.name_provider }}</td>
                            <td>{{ invoice.amount_excluding_tax }}</td>
                            <td>{{ invoice.status }}</td>
                            <td><a href="{% url 'facturasieli:invoice_details' invoice.id %}">
                                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye-fill" viewBox="0 0 16 16">
                                    <path d="M10.5 8a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/>
                                    <path d="M0 8s3-5.5 8-5.5S16 8 16 8s-3 5.5-8 5.5S0 8 0 8m8 3.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/>
                                </svg>
                            </a></td>
                        </tr>
                    {% endfor %}
                {% else %}
                <div>
                    <p>No invoice registered yet.</p>
                </div>
                {% endif %}
            </tbody>
        </table>
    </div>

</div>  
{% endblock %}